version: "3.3"

services:
  app:
    build: .
    command: python3 api2.py
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/downloads
      - ./template:/template